### ISSUE TITLE
npm Cannot find module

### ISSUE THREAD

**Issue by ding-hub** [BenZed/after-effects#22]
The new update broke my app. 

Error: Cannot find module 'after-effects'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

I had to use the old one I downloaded last week.

**Comment by BenZed** [comment]
On it.

**Comment by BenZed** [comment]
Yeah, whoops. I deleted the index.js file last publish without realizing it.

This repo really needs some tests.

Thanks for letting me know! It should work now.
